--------------------------------------------------------
--  File created - Monday-October-30-2017   
--------------------------------------------------------
DROP TABLE "USER540"."ANSWER" cascade constraints;
DROP TABLE "USER540"."ATTEMPT_SUBMISSION" cascade constraints;
DROP TABLE "USER540"."COURSE" cascade constraints;
DROP TABLE "USER540"."COURSE_STUDENT" cascade constraints;
DROP TABLE "USER540"."COURSE_TOPIC" cascade constraints;
DROP TABLE "USER540"."EXERCISE" cascade constraints;
DROP TABLE "USER540"."EXERCISE_QUESTION" cascade constraints;
DROP TABLE "USER540"."PARAMETER" cascade constraints;
DROP TABLE "USER540"."PROFESSOR" cascade constraints;
DROP TABLE "USER540"."QUESTION" cascade constraints;
DROP TABLE "USER540"."QUESTION_BANK" cascade constraints;
DROP TABLE "USER540"."QUESTION_PARAM_ANSWER" cascade constraints;
DROP TABLE "USER540"."STUDENT" cascade constraints;
DROP TABLE "USER540"."SUBMISSION_RESULT" cascade constraints;
DROP TABLE "USER540"."TA" cascade constraints;
DROP TABLE "USER540"."TOPIC" cascade constraints;
DROP SEQUENCE "USER540"."ANSWER_SEQ";
DROP SEQUENCE "USER540"."EXERCISE_SEQ";
DROP SEQUENCE "USER540"."PARAMETER_SEQ";
DROP SEQUENCE "USER540"."QUESTION_SEQ";
--------------------------------------------------------
--  DDL for Table ANSWER
--------------------------------------------------------

  CREATE TABLE "USER540"."ANSWER" 
   (	"ID" NUMBER(10,0), 
	"ANSWER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ATTEMPT_SUBMISSION
--------------------------------------------------------

  CREATE TABLE "USER540"."ATTEMPT_SUBMISSION" 
   (	"ATTEMPT_ID" NUMBER(10,0), 
	"EXERCISE_ID" NUMBER(10,0), 
	"STUDENT_ID" VARCHAR2(20 BYTE), 
	"SUBMISSION_TIME" DATE, 
	"POINTS" NUMBER(10,0), 
	"NUMBER_OF_ATTEMPTS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "USER540"."COURSE" 
   (	"COURSE_ID" VARCHAR2(20 BYTE), 
	"COURSE_NAME" VARCHAR2(100 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"PROFESSOR_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COURSE_STUDENT
--------------------------------------------------------

  CREATE TABLE "USER540"."COURSE_STUDENT" 
   (	"COURSE_ID" VARCHAR2(20 BYTE), 
	"STUDENT_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COURSE_TOPIC
--------------------------------------------------------

  CREATE TABLE "USER540"."COURSE_TOPIC" 
   (	"COURSE_ID" VARCHAR2(20 BYTE), 
	"TOPIC_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EXERCISE
--------------------------------------------------------

  CREATE TABLE "USER540"."EXERCISE" 
   (	"EXERCISE_ID" NUMBER(10,0), 
	"COURSE_ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"DEADLINE" DATE, 
	"TOTAL_QUESTIONS" NUMBER, 
	"RETRIES" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"POINTS" NUMBER, 
	"PENALTY" NUMBER, 
	"SCORING_POLICY" VARCHAR2(20 BYTE), 
	"SC_MODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EXERCISE_QUESTION
--------------------------------------------------------

  CREATE TABLE "USER540"."EXERCISE_QUESTION" 
   (	"EXERCISE_ID" NUMBER(10,0), 
	"QUESTION_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARAMETER
--------------------------------------------------------

  CREATE TABLE "USER540"."PARAMETER" 
   (	"ID" NUMBER(10,0), 
	"VALUE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFESSOR
--------------------------------------------------------

  CREATE TABLE "USER540"."PROFESSOR" 
   (	"PROFESSOR_ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUESTION
--------------------------------------------------------

  CREATE TABLE "USER540"."QUESTION" 
   (	"QUESTION_ID" NUMBER(10,0), 
	"QUESTION_TEXT" VARCHAR2(200 BYTE), 
	"DIFFICULTY_LEVEL" NUMBER, 
	"HINT" VARCHAR2(200 BYTE), 
	"EXPLANATION" VARCHAR2(200 BYTE), 
	"TOPIC_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUESTION_BANK
--------------------------------------------------------

  CREATE TABLE "USER540"."QUESTION_BANK" 
   (	"COURSE_ID" VARCHAR2(20 BYTE), 
	"QUESTION_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUESTION_PARAM_ANSWER
--------------------------------------------------------

  CREATE TABLE "USER540"."QUESTION_PARAM_ANSWER" 
   (	"QUESTION_ID" NUMBER(10,0), 
	"PARAM_ID" NUMBER(10,0), 
	"ANSWER_ID" NUMBER(10,0), 
	"CORRECT" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "USER540"."STUDENT" 
   (	"STUDENT_ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"STUDENT_LEVEL" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUBMISSION_RESULT
--------------------------------------------------------

  CREATE TABLE "USER540"."SUBMISSION_RESULT" 
   (	"ATTEMPT_ID" NUMBER(10,0), 
	"QUESTION_ID" NUMBER(10,0), 
	"GIVEN_ANSWER" VARCHAR2(100 BYTE), 
	"PARAM_ID" NUMBER(10,0), 
	"CORRECT" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TA
--------------------------------------------------------

  CREATE TABLE "USER540"."TA" 
   (	"COURSE_ID" VARCHAR2(20 BYTE), 
	"STUDENT_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TOPIC
--------------------------------------------------------

  CREATE TABLE "USER540"."TOPIC" 
   (	"TOPIC_ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence ANSWER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER540"."ANSWER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EXERCISE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER540"."EXERCISE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PARAMETER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER540"."PARAMETER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence QUESTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER540"."QUESTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Index SUBMISSION_RESULT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."SUBMISSION_RESULT_PK" ON "USER540"."SUBMISSION_RESULT" ("ATTEMPT_ID", "QUESTION_ID", "PARAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."STUDENT_PK" ON "USER540"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EXERCISE_QUESTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."EXERCISE_QUESTION_PK" ON "USER540"."EXERCISE_QUESTION" ("EXERCISE_ID", "QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ANSWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."ANSWER_PK" ON "USER540"."ANSWER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COURSE_STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."COURSE_STUDENT_PK" ON "USER540"."COURSE_STUDENT" ("COURSE_ID", "STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARAMETER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."PARAMETER_PK" ON "USER540"."PARAMETER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COURSE_TOPIC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."COURSE_TOPIC_PK" ON "USER540"."COURSE_TOPIC" ("COURSE_ID", "TOPIC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUESTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."QUESTION_PK" ON "USER540"."QUESTION" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFESSOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."PROFESSOR_PK" ON "USER540"."PROFESSOR" ("PROFESSOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUESTION_PARAM_ANSWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."QUESTION_PARAM_ANSWER_PK" ON "USER540"."QUESTION_PARAM_ANSWER" ("QUESTION_ID", "PARAM_ID", "ANSWER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TOPIC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."TOPIC_PK" ON "USER540"."TOPIC" ("TOPIC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EXERCISE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."EXERCISE_PK" ON "USER540"."EXERCISE" ("EXERCISE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."TA_PK" ON "USER540"."TA" ("COURSE_ID", "STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index QUESTION_BANK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."QUESTION_BANK_PK" ON "USER540"."QUESTION_BANK" ("COURSE_ID", "QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ATTEMPT_SUBMISSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."ATTEMPT_SUBMISSION_PK" ON "USER540"."ATTEMPT_SUBMISSION" ("ATTEMPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER540"."COURSE_PK" ON "USER540"."COURSE" ("COURSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ANSWER_PK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER540"."ANSWER_PK" 
   before insert on "USER540"."ANSWER" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select ANSWER_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "USER540"."ANSWER_PK" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EXERCISETRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER540"."EXERCISETRIGGER" 
   before insert on "USER540"."EXERCISE" 
   for each row 
begin  
   if inserting then 
      if :NEW."EXERCISE_ID" is null then 
         select EXERCISE_SEQ.nextval into :NEW."EXERCISE_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "USER540"."EXERCISETRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PARAMETER_PK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER540"."PARAMETER_PK" 
   before insert on "USER540"."PARAMETER" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select PARAMETER_SEQ.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "USER540"."PARAMETER_PK" ENABLE;
--------------------------------------------------------
--  DDL for Trigger QUESTION_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER540"."QUESTION_ID" 
   before insert on "USER540"."QUESTION" 
   for each row 
begin  
   if inserting then 
      if :NEW."QUESTION_ID" is null then 
         select QUESTION_SEQ.nextval into :NEW."QUESTION_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "USER540"."QUESTION_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table PARAMETER
--------------------------------------------------------

  ALTER TABLE "USER540"."PARAMETER" ADD CONSTRAINT "PARAMETER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."PARAMETER" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "USER540"."PARAMETER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "USER540"."STUDENT" ADD CONSTRAINT "LEVEL_CHECK" CHECK (STUDENT_LEVEL='GRADUATE' or STUDENT_LEVEL='UNDERGRADUATE') ENABLE;
  ALTER TABLE "USER540"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."STUDENT" MODIFY ("STUDENT_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "USER540"."STUDENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "USER540"."STUDENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSE_TOPIC
--------------------------------------------------------

  ALTER TABLE "USER540"."COURSE_TOPIC" ADD CONSTRAINT "COURSE_TOPIC_PK" PRIMARY KEY ("COURSE_ID", "TOPIC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."COURSE_TOPIC" MODIFY ("TOPIC_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."COURSE_TOPIC" MODIFY ("COURSE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TA
--------------------------------------------------------

  ALTER TABLE "USER540"."TA" ADD CONSTRAINT "TA_PK" PRIMARY KEY ("COURSE_ID", "STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."TA" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."TA" MODIFY ("COURSE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFESSOR
--------------------------------------------------------

  ALTER TABLE "USER540"."PROFESSOR" ADD CONSTRAINT "PROFESSOR_PK" PRIMARY KEY ("PROFESSOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."PROFESSOR" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "USER540"."PROFESSOR" MODIFY ("PROFESSOR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "USER540"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("COURSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."COURSE" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "USER540"."COURSE" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "USER540"."COURSE" MODIFY ("COURSE_NAME" NOT NULL ENABLE);
  ALTER TABLE "USER540"."COURSE" MODIFY ("COURSE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXERCISE_QUESTION
--------------------------------------------------------

  ALTER TABLE "USER540"."EXERCISE_QUESTION" ADD CONSTRAINT "EXERCISE_QUESTION_PK" PRIMARY KEY ("EXERCISE_ID", "QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."EXERCISE_QUESTION" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."EXERCISE_QUESTION" MODIFY ("EXERCISE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANSWER
--------------------------------------------------------

  ALTER TABLE "USER540"."ANSWER" ADD CONSTRAINT "ANSWER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."ANSWER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTEMPT_SUBMISSION
--------------------------------------------------------

  ALTER TABLE "USER540"."ATTEMPT_SUBMISSION" ADD CONSTRAINT "ATTEMPT_SUBMISSION_PK" PRIMARY KEY ("ATTEMPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."ATTEMPT_SUBMISSION" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."ATTEMPT_SUBMISSION" MODIFY ("EXERCISE_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."ATTEMPT_SUBMISSION" MODIFY ("ATTEMPT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSE_STUDENT
--------------------------------------------------------

  ALTER TABLE "USER540"."COURSE_STUDENT" ADD CONSTRAINT "COURSE_STUDENT_PK" PRIMARY KEY ("COURSE_ID", "STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."COURSE_STUDENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."COURSE_STUDENT" MODIFY ("COURSE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOPIC
--------------------------------------------------------

  ALTER TABLE "USER540"."TOPIC" ADD CONSTRAINT "TOPIC_PK" PRIMARY KEY ("TOPIC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."TOPIC" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "USER540"."TOPIC" MODIFY ("TOPIC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUESTION_BANK
--------------------------------------------------------

  ALTER TABLE "USER540"."QUESTION_BANK" ADD CONSTRAINT "QUESTION_BANK_PK" PRIMARY KEY ("COURSE_ID", "QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."QUESTION_BANK" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."QUESTION_BANK" MODIFY ("COURSE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBMISSION_RESULT
--------------------------------------------------------

  ALTER TABLE "USER540"."SUBMISSION_RESULT" ADD CONSTRAINT "SUBMISSION_RESULT_PK" PRIMARY KEY ("ATTEMPT_ID", "QUESTION_ID", "PARAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."SUBMISSION_RESULT" MODIFY ("PARAM_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."SUBMISSION_RESULT" MODIFY ("GIVEN_ANSWER" NOT NULL ENABLE);
  ALTER TABLE "USER540"."SUBMISSION_RESULT" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."SUBMISSION_RESULT" MODIFY ("ATTEMPT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUESTION_PARAM_ANSWER
--------------------------------------------------------

  ALTER TABLE "USER540"."QUESTION_PARAM_ANSWER" ADD CONSTRAINT "QUESTION_PARAM_ANSWER_PK" PRIMARY KEY ("QUESTION_ID", "PARAM_ID", "ANSWER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."QUESTION_PARAM_ANSWER" MODIFY ("CORRECT" NOT NULL ENABLE);
  ALTER TABLE "USER540"."QUESTION_PARAM_ANSWER" MODIFY ("ANSWER_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."QUESTION_PARAM_ANSWER" MODIFY ("PARAM_ID" NOT NULL ENABLE);
  ALTER TABLE "USER540"."QUESTION_PARAM_ANSWER" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXERCISE
--------------------------------------------------------

  ALTER TABLE "USER540"."EXERCISE" ADD CONSTRAINT "EXERCISE_PK" PRIMARY KEY ("EXERCISE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."EXERCISE" MODIFY ("COURSE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUESTION
--------------------------------------------------------

  ALTER TABLE "USER540"."QUESTION" ADD CONSTRAINT "QUESTION_PK" PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER540"."QUESTION" ADD CONSTRAINT "QUESTION_CHK1" CHECK (difficulty_level >=1 and difficulty_level <=6 ) ENABLE;
  ALTER TABLE "USER540"."QUESTION" MODIFY ("DIFFICULTY_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "USER540"."QUESTION" MODIFY ("QUESTION_TEXT" NOT NULL ENABLE);
  ALTER TABLE "USER540"."QUESTION" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTEMPT_SUBMISSION
--------------------------------------------------------

  ALTER TABLE "USER540"."ATTEMPT_SUBMISSION" ADD CONSTRAINT "ATTEMPT_SUBMISSION_FK1" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "USER540"."STUDENT" ("STUDENT_ID") ENABLE;
  ALTER TABLE "USER540"."ATTEMPT_SUBMISSION" ADD CONSTRAINT "ATTEMPT_SUBMISSION_FK2" FOREIGN KEY ("EXERCISE_ID")
	  REFERENCES "USER540"."EXERCISE" ("EXERCISE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "USER540"."COURSE" ADD CONSTRAINT "COURSE_FK1" FOREIGN KEY ("PROFESSOR_ID")
	  REFERENCES "USER540"."PROFESSOR" ("PROFESSOR_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURSE_STUDENT
--------------------------------------------------------

  ALTER TABLE "USER540"."COURSE_STUDENT" ADD CONSTRAINT "COURSE_STUDENT_FK1" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "USER540"."COURSE" ("COURSE_ID") ENABLE;
  ALTER TABLE "USER540"."COURSE_STUDENT" ADD CONSTRAINT "COURSE_STUDENT_FK2" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "USER540"."STUDENT" ("STUDENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURSE_TOPIC
--------------------------------------------------------

  ALTER TABLE "USER540"."COURSE_TOPIC" ADD CONSTRAINT "COURSE_TOPIC_FK1" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "USER540"."COURSE" ("COURSE_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "USER540"."COURSE_TOPIC" ADD CONSTRAINT "COURSE_TOPIC_FK2" FOREIGN KEY ("TOPIC_ID")
	  REFERENCES "USER540"."TOPIC" ("TOPIC_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXERCISE
--------------------------------------------------------

  ALTER TABLE "USER540"."EXERCISE" ADD CONSTRAINT "EXERCISE_FK1" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "USER540"."COURSE" ("COURSE_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXERCISE_QUESTION
--------------------------------------------------------

  ALTER TABLE "USER540"."EXERCISE_QUESTION" ADD CONSTRAINT "EXERCISE_QUESTION_FK1" FOREIGN KEY ("EXERCISE_ID")
	  REFERENCES "USER540"."EXERCISE" ("EXERCISE_ID") ENABLE;
  ALTER TABLE "USER540"."EXERCISE_QUESTION" ADD CONSTRAINT "EXERCISE_QUESTION_FK2" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "USER540"."QUESTION" ("QUESTION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUESTION
--------------------------------------------------------

  ALTER TABLE "USER540"."QUESTION" ADD CONSTRAINT "QUESTION_FK1" FOREIGN KEY ("TOPIC_ID")
	  REFERENCES "USER540"."TOPIC" ("TOPIC_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUESTION_BANK
--------------------------------------------------------

  ALTER TABLE "USER540"."QUESTION_BANK" ADD CONSTRAINT "QUESTION_BANK_FK1" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "USER540"."QUESTION" ("QUESTION_ID") ENABLE;
  ALTER TABLE "USER540"."QUESTION_BANK" ADD CONSTRAINT "QUESTION_BANK_FK2" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "USER540"."COURSE" ("COURSE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUESTION_PARAM_ANSWER
--------------------------------------------------------

  ALTER TABLE "USER540"."QUESTION_PARAM_ANSWER" ADD CONSTRAINT "QUESTION_PARAM_ANSWER_FK1" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "USER540"."QUESTION" ("QUESTION_ID") ENABLE;
  ALTER TABLE "USER540"."QUESTION_PARAM_ANSWER" ADD CONSTRAINT "QUESTION_PARAM_ANSWER_FK2" FOREIGN KEY ("PARAM_ID")
	  REFERENCES "USER540"."PARAMETER" ("ID") ENABLE;
  ALTER TABLE "USER540"."QUESTION_PARAM_ANSWER" ADD CONSTRAINT "QUESTION_PARAM_ANSWER_FK3" FOREIGN KEY ("ANSWER_ID")
	  REFERENCES "USER540"."ANSWER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBMISSION_RESULT
--------------------------------------------------------

  ALTER TABLE "USER540"."SUBMISSION_RESULT" ADD CONSTRAINT "SUBMISSION_RESULT_FK1" FOREIGN KEY ("ATTEMPT_ID")
	  REFERENCES "USER540"."ATTEMPT_SUBMISSION" ("ATTEMPT_ID") ENABLE;
  ALTER TABLE "USER540"."SUBMISSION_RESULT" ADD CONSTRAINT "SUBMISSION_RESULT_FK2" FOREIGN KEY ("PARAM_ID")
	  REFERENCES "USER540"."PARAMETER" ("ID") ENABLE;
  ALTER TABLE "USER540"."SUBMISSION_RESULT" ADD CONSTRAINT "SUBMISSION_RESULT_FK3" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "USER540"."QUESTION" ("QUESTION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TA
--------------------------------------------------------

  ALTER TABLE "USER540"."TA" ADD CONSTRAINT "TA_FK_1" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "USER540"."COURSE" ("COURSE_ID") ENABLE;
  ALTER TABLE "USER540"."TA" ADD CONSTRAINT "TA_FK_2" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "USER540"."STUDENT" ("STUDENT_ID") ENABLE;
